// Recipes
export const SET_SEARCHED_RECIPES = 'SET_SEARCHED_RECIPES'

// Navigation
export const SET_TAB = 'SET_TAB'

export const NAVIGATION_FORWARD = 'NAVIGATION_FORWARD'
export const NAVIGATION_BACK = 'NAVIGATION_BACK'
export const INPUTED_EMAIL = 'INPUTED_EMAIL'
export const INPUTED_PASSWORD = 'INPUTED_PASSWORD'
export const SAVED_EMAIL = 'SAVED_EMAIL'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
export const LOADING = 'LOADING'
export const UNLOADING = 'UNLOADING'
export const USERNAME_LIST = 'USERNAME_LIST'
export const MY_USERNAME = 'MY_USERNAME'
export const SELECT_GAME_ROOM = 'SELECT_GAME_ROOM'
export const ALL_POSTS = 'ALL_POSTS'